### ISSUE TITLE
Why are Mac builds disabled on Travis

### ISSUE THREAD

**Issue by andfoy** [conda-forge/spyder-terminal-feedstock#1]
It seems that we're not building packages for Mac @ccordoba12

**Comment by goanpeca** [comment]
I think @ccordoba12 disabled because travis Mac VMs for Open source are always queued in the order of hours.

**Comment by andfoy** [comment]
So it means that we won't serve Mac packages on conda?

**Comment by goanpeca** [comment]
Ah no wait, I thought we were in our repos not in the feedstock. Hmm there must be an error!

**Comment by andfoy** [comment]
I've just started the build, for some reason it didn't got to execute when the feedstock was re-rendered

**Comment by andfoy** [comment]
Mac packages are now available, closing this one.
